Stable logging baseline
SovereignAI/roboteq_diff_driver pull request #4
Opened 2021-12-21 15:33 UTC by teddyort

2021-12-21 20:43 UTC, GoldenZephyr requested changes
[ ] wheel_rate(s)
[ ] scale factor 10 parameter
[ ] loop sleep parameter
[ ] serial timeout parameter

2021-12-21 20:43 UTC, GoldenZephyr commented on roboteq_diff_driver/src/driver.cpp
> +
standardize wheel rate vs wheel rates

2021-12-21 20:43 UTC, GoldenZephyr commented on roboteq_diff_driver/src/driver.cpp
> +    int32_t right_rpm = right_speed / wheel_circumference * 60.0 * 10.0;
change 10 to a param (?)

2021-12-21 20:43 UTC, GoldenZephyr commented on roboteq_diff_driver/src/driver.cpp
> +  ros::Rate loop_rate(500);
make loop rate a parameter

2021-12-21 20:43 UTC, GoldenZephyr commented on roboteq_diff_driver/src/driver.cpp
> +  while (controller.available() && DELTAT(millis(), nowtime) < 20)
set 20ms to be configurable

2021-12-21 22:23 UTC, GoldenZephyr commented on roboteq_diff_driver/src/driver.cpp
> +
This change would be a pain and conflicts with some near-future changes that actually remove these wheel rate messages, so it's not worth changing this right now.

2021-12-21 22:30 UTC, GoldenZephyr commented on roboteq_diff_driver/src/driver.cpp
> +    int32_t right_rpm = right_speed / wheel_circumference * 60.0 * roboteq_rpm_scale;
Scale factor is now a ros param

2021-12-21 22:31 UTC, GoldenZephyr commented on roboteq_diff_driver/src/driver.cpp
> +  while (controller.available() && DELTAT(millis(), nowtime) < serial_timeout_ms)
timeout is now a ros param

2021-12-21 22:31 UTC, GoldenZephyr commented on roboteq_diff_driver/src/driver.cpp
> +  ros::Rate loop_rate(ros_loop_rate);
loop rate is now a ros param

2021-12-21 22:33 UTC, GoldenZephyr approved these changes
Fixed the things Teddy and I discussed earlier

2021-12-22 21:34 UTC, teddyort reviewed
LGTM Please test if necessary and then merge

2021-12-30 19:00 UTC, merged